// Copyright (C) 2005-2008 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include "SCL_BaseSimpleTypes-pskel.h"

namespace IEC61850
{
  namespace SCL
  {
    namespace Validation
    {
    }
  }
}

namespace IEC61850
{
  namespace SCL
  {
    namespace Validation
    {
      // tRef_pskel
      //

      void tRef_pskel::
      post_tRef ()
      {
      }

      // tAnyName_pskel
      //

      void tAnyName_pskel::
      post_tAnyName ()
      {
      }

      // tName_pskel
      //

      void tName_pskel::
      post_tName ()
      {
        post_tAnyName ();
      }

      // tRestrName_pskel
      //

      void tRestrName_pskel::
      post_tRestrName ()
      {
      }

      // tRestrLdName_pskel
      //

      void tRestrLdName_pskel::
      post_tRestrLdName ()
      {
      }

      // tRestrName1stU_pskel
      //

      void tRestrName1stU_pskel::
      post_tRestrName1stU ()
      {
      }

      // tRestrName1stL_pskel
      //

      void tRestrName1stL_pskel::
      post_tRestrName1stL ()
      {
      }

      // tPAddr_pskel
      //

      void tPAddr_pskel::
      post_tPAddr ()
      {
      }
    }
  }
}

#include <cassert>

namespace IEC61850
{
  namespace SCL
  {
    namespace Validation
    {
    }
  }
}

namespace IEC61850
{
  namespace SCL
  {
    namespace Validation
    {
    }
  }
}

namespace IEC61850
{
  namespace SCL
  {
    namespace Validation
    {
    }
  }
}

// Begin epilogue.
//
//
// End epilogue.

