// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenSASUI {
    
    
    public partial class SclCommManager {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button ipupdate;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView iptreeview;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button updategse;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView gsetreeview;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label6;
        
        private Gtk.Label label5;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenSASUI.SclCommManager
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenSASUI.SclCommManager";
            // Container child OpenSASUI.SclCommManager.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 1;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.ipupdate = new Gtk.Button();
            this.ipupdate.CanFocus = true;
            this.ipupdate.Name = "ipupdate";
            this.ipupdate.UseStock = true;
            this.ipupdate.UseUnderline = true;
            this.ipupdate.Label = "gtk-refresh";
            this.hbox1.Add(this.ipupdate);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.ipupdate]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.iptreeview = new Gtk.TreeView();
            this.iptreeview.CanFocus = true;
            this.iptreeview.Name = "iptreeview";
            this.GtkScrolledWindow.Add(this.iptreeview);
            this.vbox1.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
            w4.Position = 1;
            this.notebook1.Add(this.vbox1);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("TCP/IP");
            this.notebook1.SetTabLabel(this.vbox1, this.label2);
            this.label2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.updategse = new Gtk.Button();
            this.updategse.CanFocus = true;
            this.updategse.Name = "updategse";
            this.updategse.UseStock = true;
            this.updategse.UseUnderline = true;
            this.updategse.Label = "gtk-refresh";
            this.hbox2.Add(this.updategse);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.updategse]));
            w6.Position = 0;
            w6.Expand = false;
            w6.Fill = false;
            this.vbox4.Add(this.hbox2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.gsetreeview = new Gtk.TreeView();
            this.gsetreeview.CanFocus = true;
            this.gsetreeview.Name = "gsetreeview";
            this.GtkScrolledWindow1.Add(this.gsetreeview);
            this.vbox4.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow1]));
            w9.Position = 1;
            this.notebook1.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w10 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
            w10.Position = 1;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("GOOSE");
            this.notebook1.SetTabLabel(this.vbox4, this.label3);
            this.label3.ShowAll();
            // Notebook tab
            Gtk.Label w11 = new Gtk.Label();
            w11.Visible = true;
            this.notebook1.Add(w11);
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("SMV");
            this.notebook1.SetTabLabel(w11, this.label4);
            this.label4.ShowAll();
            // Notebook tab
            Gtk.Label w12 = new Gtk.Label();
            w12.Visible = true;
            this.notebook1.Add(w12);
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Reports");
            this.notebook1.SetTabLabel(w12, this.label6);
            this.label6.ShowAll();
            // Notebook tab
            Gtk.Label w13 = new Gtk.Label();
            w13.Visible = true;
            this.notebook1.Add(w13);
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("DataSet");
            this.notebook1.SetTabLabel(w13, this.label5);
            this.label5.ShowAll();
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
