// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenSASUI {
    
    
    public partial class GSEditor {
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button updategse;
        
        private Gtk.Button updategsetype;
        
        private Gtk.Button addgse;
        
        private Gtk.Button removegse;
        
        private Gtk.Button gseedit;
        
        private Gtk.HPaned hpaned2;
        
        private Gtk.VBox vbox10;
        
        private Gtk.Label label11;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView gsetreeview;
        
        private Gtk.VBox vbox11;
        
        private Gtk.Label label12;
        
        private Gtk.ScrolledWindow GtkScrolledWindow6;
        
        private Gtk.TreeView gsedetailstreeview;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenSASUI.GSEditor
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenSASUI.GSEditor";
            // Container child OpenSASUI.GSEditor.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.updategse = new Gtk.Button();
            this.updategse.CanFocus = true;
            this.updategse.Name = "updategse";
            this.updategse.UseStock = true;
            this.updategse.UseUnderline = true;
            this.updategse.Label = "gtk-refresh";
            this.hbox2.Add(this.updategse);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.updategse]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.updategsetype = new Gtk.Button();
            this.updategsetype.TooltipMarkup = "Show GSE's types from IED's information";
            this.updategsetype.CanFocus = true;
            this.updategsetype.Name = "updategsetype";
            this.updategsetype.UseUnderline = true;
            // Container child updategsetype.Gtk.Container+ContainerChild
            Gtk.Alignment w2 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w3 = new Gtk.HBox();
            w3.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w4 = new Gtk.Image();
            w4.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-refresh", Gtk.IconSize.Menu, 16);
            w3.Add(w4);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w6 = new Gtk.Label();
            w6.LabelProp = Mono.Unix.Catalog.GetString("GSE Types");
            w6.UseUnderline = true;
            w3.Add(w6);
            w2.Add(w3);
            this.updategsetype.Add(w2);
            this.hbox2.Add(this.updategsetype);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox2[this.updategsetype]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.addgse = new Gtk.Button();
            this.addgse.CanFocus = true;
            this.addgse.Name = "addgse";
            this.addgse.UseStock = true;
            this.addgse.UseUnderline = true;
            this.addgse.Label = "gtk-add";
            this.hbox2.Add(this.addgse);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox2[this.addgse]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.removegse = new Gtk.Button();
            this.removegse.CanFocus = true;
            this.removegse.Name = "removegse";
            this.removegse.UseStock = true;
            this.removegse.UseUnderline = true;
            this.removegse.Label = "gtk-remove";
            this.hbox2.Add(this.removegse);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox2[this.removegse]));
            w12.Position = 3;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.gseedit = new Gtk.Button();
            this.gseedit.CanFocus = true;
            this.gseedit.Name = "gseedit";
            this.gseedit.UseStock = true;
            this.gseedit.UseUnderline = true;
            this.gseedit.Label = "gtk-edit";
            this.hbox2.Add(this.gseedit);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox2[this.gseedit]));
            w13.Position = 4;
            w13.Expand = false;
            w13.Fill = false;
            this.vbox4.Add(this.hbox2);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
            w14.Position = 0;
            w14.Expand = false;
            w14.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hpaned2 = new Gtk.HPaned();
            this.hpaned2.CanFocus = true;
            this.hpaned2.Name = "hpaned2";
            this.hpaned2.Position = 350;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.vbox10 = new Gtk.VBox();
            this.vbox10.Name = "vbox10";
            this.vbox10.Spacing = 6;
            // Container child vbox10.Gtk.Box+BoxChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("GSE Information");
            this.vbox10.Add(this.label11);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox10[this.label11]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Container child vbox10.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.gsetreeview = new Gtk.TreeView();
            this.gsetreeview.CanFocus = true;
            this.gsetreeview.Name = "gsetreeview";
            this.GtkScrolledWindow1.Add(this.gsetreeview);
            this.vbox10.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow1]));
            w17.Position = 1;
            this.hpaned2.Add(this.vbox10);
            Gtk.Paned.PanedChild w18 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.vbox10]));
            w18.Resize = false;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.vbox11 = new Gtk.VBox();
            this.vbox11.Name = "vbox11";
            this.vbox11.Spacing = 6;
            // Container child vbox11.Gtk.Box+BoxChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Details");
            this.vbox11.Add(this.label12);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox11[this.label12]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Container child vbox11.Gtk.Box+BoxChild
            this.GtkScrolledWindow6 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
            this.GtkScrolledWindow6.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
            this.gsedetailstreeview = new Gtk.TreeView();
            this.gsedetailstreeview.TooltipMarkup = "GSE Details. List DataSet information and IED recommended to be suscribed to this GSE.";
            this.gsedetailstreeview.CanFocus = true;
            this.gsedetailstreeview.Name = "gsedetailstreeview";
            this.GtkScrolledWindow6.Add(this.gsedetailstreeview);
            this.vbox11.Add(this.GtkScrolledWindow6);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox11[this.GtkScrolledWindow6]));
            w21.Position = 1;
            this.hpaned2.Add(this.vbox11);
            this.vbox4.Add(this.hpaned2);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox4[this.hpaned2]));
            w23.Position = 1;
            this.Add(this.vbox4);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
