
// This file has been generated by the GUI designer. Do not modify.
namespace OpenSASUI
{
	public partial class GSEditor
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenSASUI.GSEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OpenSASUI.GSEditor";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
