// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenSASUI {
    
    
    public partial class SclEditor {
        
        private Gtk.HPaned hpaned3;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private OpenSASUI.SclTreeView scltreeview;
        
        private Gtk.Notebook notebook2;
        
        private Gtk.VBox NothingContainer;
        
        private Gtk.Label label4;
        
        private OpenSASUI.IEDEditor iededitor;
        
        private Gtk.Label label26;
        
        private Gtk.VBox vbox10;
        
        private OpenSASUI.SclCommManager sclcommmanager;
        
        private Gtk.Label label35;
        
        private OpenSASUI.HistoryEditor historyeditor;
        
        private Gtk.Label label36;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenSASUI.SclEditor
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenSASUI.SclEditor";
            // Container child OpenSASUI.SclEditor.Gtk.Container+ContainerChild
            this.hpaned3 = new Gtk.HPaned();
            this.hpaned3.CanFocus = true;
            this.hpaned3.Name = "hpaned3";
            this.hpaned3.Position = 218;
            // Container child hpaned3.Gtk.Paned+PanedChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.scltreeview = new OpenSASUI.SclTreeView();
            this.scltreeview.CanFocus = true;
            this.scltreeview.Name = "scltreeview";
            this.scrolledwindow1.Add(this.scltreeview);
            this.hpaned3.Add(this.scrolledwindow1);
            Gtk.Paned.PanedChild w2 = ((Gtk.Paned.PanedChild)(this.hpaned3[this.scrolledwindow1]));
            w2.Resize = false;
            // Container child hpaned3.Gtk.Paned+PanedChild
            this.notebook2 = new Gtk.Notebook();
            this.notebook2.CanFocus = true;
            this.notebook2.Name = "notebook2";
            this.notebook2.CurrentPage = 3;
            // Container child notebook2.Gtk.Notebook+NotebookChild
            this.NothingContainer = new Gtk.VBox();
            this.NothingContainer.Name = "NothingContainer";
            this.NothingContainer.Spacing = 6;
            this.notebook2.Add(this.NothingContainer);
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Nothing");
            this.notebook2.SetTabLabel(this.NothingContainer, this.label4);
            this.label4.ShowAll();
            // Container child notebook2.Gtk.Notebook+NotebookChild
            this.iededitor = new OpenSASUI.IEDEditor();
            this.iededitor.Events = ((Gdk.EventMask)(256));
            this.iededitor.Name = "iededitor";
            this.notebook2.Add(this.iededitor);
            Gtk.Notebook.NotebookChild w4 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.iededitor]));
            w4.Position = 1;
            w4.TabExpand = true;
            // Notebook tab
            this.label26 = new Gtk.Label();
            this.label26.Name = "label26";
            this.label26.LabelProp = Mono.Unix.Catalog.GetString("IED Editor");
            this.notebook2.SetTabLabel(this.iededitor, this.label26);
            this.label26.ShowAll();
            // Container child notebook2.Gtk.Notebook+NotebookChild
            this.vbox10 = new Gtk.VBox();
            this.vbox10.Name = "vbox10";
            this.vbox10.Spacing = 6;
            // Container child vbox10.Gtk.Box+BoxChild
            this.sclcommmanager = new OpenSASUI.SclCommManager();
            this.sclcommmanager.Events = ((Gdk.EventMask)(256));
            this.sclcommmanager.Name = "sclcommmanager";
            this.vbox10.Add(this.sclcommmanager);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox10[this.sclcommmanager]));
            w5.Position = 0;
            this.notebook2.Add(this.vbox10);
            Gtk.Notebook.NotebookChild w6 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox10]));
            w6.Position = 2;
            // Notebook tab
            this.label35 = new Gtk.Label();
            this.label35.Name = "label35";
            this.label35.LabelProp = Mono.Unix.Catalog.GetString("Communications");
            this.notebook2.SetTabLabel(this.vbox10, this.label35);
            this.label35.ShowAll();
            // Container child notebook2.Gtk.Notebook+NotebookChild
            this.historyeditor = new OpenSASUI.HistoryEditor();
            this.historyeditor.Events = ((Gdk.EventMask)(256));
            this.historyeditor.Name = "historyeditor";
            this.notebook2.Add(this.historyeditor);
            Gtk.Notebook.NotebookChild w7 = ((Gtk.Notebook.NotebookChild)(this.notebook2[this.historyeditor]));
            w7.Position = 3;
            // Notebook tab
            this.label36 = new Gtk.Label();
            this.label36.Name = "label36";
            this.label36.LabelProp = Mono.Unix.Catalog.GetString("History");
            this.notebook2.SetTabLabel(this.historyeditor, this.label36);
            this.label36.ShowAll();
            this.hpaned3.Add(this.notebook2);
            this.Add(this.hpaned3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
