// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenSASUI {
    
    
    public partial class SclCommManager {
        
        private Gtk.VBox vbox2;
        
        private OpenSASUI.SubnetworkEditor subnetworkeditor1;
        
        private Gtk.Notebook notebook1;
        
        private OpenSASUI.IPListViewer iplistviewer;
        
        private Gtk.Label label2;
        
        private OpenSASUI.GSEListViewer gselistviewer;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private OpenSASUI.ReportListViewer reportlistviewer;
        
        private Gtk.Label label13;
        
        private Gtk.Label label9;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenSASUI.SclCommManager
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenSASUI.SclCommManager";
            // Container child OpenSASUI.SclCommManager.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.subnetworkeditor1 = new OpenSASUI.SubnetworkEditor();
            this.subnetworkeditor1.Events = ((Gdk.EventMask)(256));
            this.subnetworkeditor1.Name = "subnetworkeditor1";
            this.vbox2.Add(this.subnetworkeditor1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.subnetworkeditor1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 3;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.iplistviewer = new OpenSASUI.IPListViewer();
            this.iplistviewer.Events = ((Gdk.EventMask)(256));
            this.iplistviewer.Name = "iplistviewer";
            this.notebook1.Add(this.iplistviewer);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.TooltipMarkup = "IP address list";
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("TCP/IP");
            this.notebook1.SetTabLabel(this.iplistviewer, this.label2);
            this.label2.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.gselistviewer = new OpenSASUI.GSEListViewer();
            this.gselistviewer.Events = ((Gdk.EventMask)(256));
            this.gselistviewer.Name = "gselistviewer";
            this.notebook1.Add(this.gselistviewer);
            Gtk.Notebook.NotebookChild w3 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.gselistviewer]));
            w3.Position = 1;
            // Notebook tab
            this.label7 = new Gtk.Label();
            this.label7.TooltipMarkup = "GOOSE and GSSE";
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("GSE");
            this.notebook1.SetTabLabel(this.gselistviewer, this.label7);
            this.label7.ShowAll();
            // Notebook tab
            Gtk.Label w4 = new Gtk.Label();
            w4.Visible = true;
            this.notebook1.Add(w4);
            this.label8 = new Gtk.Label();
            this.label8.TooltipMarkup = "Lists of Sample Values";
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("SMV");
            this.notebook1.SetTabLabel(w4, this.label8);
            this.label8.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.reportlistviewer = new OpenSASUI.ReportListViewer();
            this.reportlistviewer.Events = ((Gdk.EventMask)(256));
            this.reportlistviewer.Name = "reportlistviewer";
            this.notebook1.Add(this.reportlistviewer);
            Gtk.Notebook.NotebookChild w5 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.reportlistviewer]));
            w5.Position = 3;
            // Notebook tab
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("Reports");
            this.notebook1.SetTabLabel(this.reportlistviewer, this.label13);
            this.label13.ShowAll();
            // Notebook tab
            Gtk.Label w6 = new Gtk.Label();
            w6.Visible = true;
            this.notebook1.Add(w6);
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("DataSet");
            this.notebook1.SetTabLabel(w6, this.label9);
            this.label9.ShowAll();
            this.vbox2.Add(this.notebook1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
            w7.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
