// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenSASUI {
    
    
    public partial class APEditor {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Expander accesspointdetails;
        
        private Gtk.Table table2;
        
        private Gtk.Entry accesspointdesc;
        
        private Gtk.CheckButton accesspointisclock;
        
        private Gtk.CheckButton accesspointisrouter;
        
        private Gtk.Entry accesspointname;
        
        private Gtk.Expander aplndetails;
        
        private Gtk.HBox hbox3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow1;
        
        private Gtk.TreeView aplntreeview;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Button addapln;
        
        private Gtk.Button removeapln;
        
        private Gtk.Button propertiesapln;
        
        private Gtk.Label GtkLabel3;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Label GtkLabel6;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Label label10;
        
        private Gtk.ComboBox subnetworklist;
        
        private Gtk.Button propertiessubnet;
        
        private Gtk.Button connectsubnet;
        
        private Gtk.Button desconnectsubnet;
        
        private Gtk.Expander connectiondetails;
        
        private Gtk.Notebook notebook;
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView addresstreeview;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button addp_address;
        
        private Gtk.Button removep_address;
        
        private Gtk.Table table1;
        
        private Gtk.Entry addressvalue;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Button manageaddress;
        
        private Gtk.ComboBoxEntry tplist;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.ComboBox physclist;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button addphysconn;
        
        private Gtk.Button removephysconn;
        
        private Gtk.Button editphysconn;
        
        private Gtk.HPaned hpaned2;
        
        private Gtk.VBox vbox5;
        
        private Gtk.ScrolledWindow GtkScrolledWindow2;
        
        private Gtk.TreeView physicaltreeview;
        
        private Gtk.HButtonBox hbuttonbox3;
        
        private Gtk.Button addp_physconn;
        
        private Gtk.Button removep_physconn;
        
        private Gtk.Table table3;
        
        private Gtk.Label label11;
        
        private Gtk.Label label12;
        
        private Gtk.Button managephysicalconnections;
        
        private Gtk.Entry physicalvalue;
        
        private Gtk.ComboBoxEntry tplist_physical;
        
        private Gtk.Label label5;
        
        private OpenSASUI.GSEListViewer gselistviewer;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label GtkLabel23;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget OpenSASUI.APEditor
            Stetic.BinContainer.Attach(this);
            this.Name = "OpenSASUI.APEditor";
            // Container child OpenSASUI.APEditor.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.accesspointdetails = new Gtk.Expander(null);
            this.accesspointdetails.CanFocus = true;
            this.accesspointdetails.Name = "accesspointdetails";
            this.accesspointdetails.Expanded = true;
            // Container child accesspointdetails.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.accesspointdesc = new Gtk.Entry();
            this.accesspointdesc.CanFocus = true;
            this.accesspointdesc.Name = "accesspointdesc";
            this.accesspointdesc.IsEditable = true;
            this.accesspointdesc.InvisibleChar = '●';
            this.table2.Add(this.accesspointdesc);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table2[this.accesspointdesc]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.accesspointisclock = new Gtk.CheckButton();
            this.accesspointisclock.TooltipMarkup = "Is a Clock? <FIXME>";
            this.accesspointisclock.CanFocus = true;
            this.accesspointisclock.Name = "accesspointisclock";
            this.accesspointisclock.Label = Mono.Unix.Catalog.GetString("Is Clock");
            this.accesspointisclock.DrawIndicator = true;
            this.accesspointisclock.UseUnderline = true;
            this.table2.Add(this.accesspointisclock);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table2[this.accesspointisclock]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.accesspointisrouter = new Gtk.CheckButton();
            this.accesspointisrouter.CanFocus = true;
            this.accesspointisrouter.Name = "accesspointisrouter";
            this.accesspointisrouter.Label = Mono.Unix.Catalog.GetString("Is Router");
            this.accesspointisrouter.DrawIndicator = true;
            this.accesspointisrouter.UseUnderline = true;
            this.table2.Add(this.accesspointisrouter);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.accesspointisrouter]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.accesspointname = new Gtk.Entry();
            this.accesspointname.CanFocus = true;
            this.accesspointname.Name = "accesspointname";
            this.accesspointname.IsEditable = true;
            this.accesspointname.InvisibleChar = '●';
            this.table2.Add(this.accesspointname);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.accesspointname]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.aplndetails = new Gtk.Expander(null);
            this.aplndetails.CanFocus = true;
            this.aplndetails.Name = "aplndetails";
            this.aplndetails.Expanded = true;
            // Container child aplndetails.Gtk.Container+ContainerChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.GtkScrolledWindow1 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
            this.GtkScrolledWindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
            this.aplntreeview = new Gtk.TreeView();
            this.aplntreeview.CanFocus = true;
            this.aplntreeview.Name = "aplntreeview";
            this.GtkScrolledWindow1.Add(this.aplntreeview);
            this.hbox3.Add(this.GtkScrolledWindow1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow1]));
            w6.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.addapln = new Gtk.Button();
            this.addapln.CanFocus = true;
            this.addapln.Name = "addapln";
            this.addapln.UseStock = true;
            this.addapln.UseUnderline = true;
            this.addapln.Label = "gtk-add";
            this.vbox2.Add(this.addapln);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox2[this.addapln]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.removeapln = new Gtk.Button();
            this.removeapln.CanFocus = true;
            this.removeapln.Name = "removeapln";
            this.removeapln.UseStock = true;
            this.removeapln.UseUnderline = true;
            this.removeapln.Label = "gtk-remove";
            this.vbox2.Add(this.removeapln);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.removeapln]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.propertiesapln = new Gtk.Button();
            this.propertiesapln.CanFocus = true;
            this.propertiesapln.Name = "propertiesapln";
            this.propertiesapln.UseStock = true;
            this.propertiesapln.UseUnderline = true;
            this.propertiesapln.Label = "gtk-properties";
            this.vbox2.Add(this.propertiesapln);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.propertiesapln]));
            w9.Position = 2;
            w9.Expand = false;
            w9.Fill = false;
            this.hbox3.Add(this.vbox2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.vbox2]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.aplndetails.Add(this.hbox3);
            this.GtkLabel3 = new Gtk.Label();
            this.GtkLabel3.Name = "GtkLabel3";
            this.GtkLabel3.LabelProp = Mono.Unix.Catalog.GetString("Logical Nodes in AP");
            this.GtkLabel3.UseUnderline = true;
            this.aplndetails.LabelWidget = this.GtkLabel3;
            this.table2.Add(this.aplndetails);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table2[this.aplndetails]));
            w12.TopAttach = ((uint)(3));
            w12.BottomAttach = ((uint)(4));
            w12.RightAttach = ((uint)(2));
            // Container child table2.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.table2.Add(this.label8);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table2[this.label8]));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Description:");
            this.table2.Add(this.label9);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table2[this.label9]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            this.accesspointdetails.Add(this.table2);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("Access Point Details");
            this.GtkLabel6.UseUnderline = true;
            this.accesspointdetails.LabelWidget = this.GtkLabel6;
            this.vbox1.Add(this.accesspointdetails);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.accesspointdetails]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Spacing = 6;
            // Container child hbox4.Gtk.Box+BoxChild
            this.label10 = new Gtk.Label();
            this.label10.TooltipMarkup = "The Subnetwork name this Access Point is Connected to";
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Subnetwork:");
            this.hbox4.Add(this.label10);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox4[this.label10]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.subnetworklist = Gtk.ComboBox.NewText();
            this.subnetworklist.Name = "subnetworklist";
            this.hbox4.Add(this.subnetworklist);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox4[this.subnetworklist]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.propertiessubnet = new Gtk.Button();
            this.propertiessubnet.CanFocus = true;
            this.propertiessubnet.Name = "propertiessubnet";
            this.propertiessubnet.UseStock = true;
            this.propertiessubnet.UseUnderline = true;
            this.propertiessubnet.Label = "gtk-properties";
            this.hbox4.Add(this.propertiessubnet);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox4[this.propertiessubnet]));
            w19.PackType = ((Gtk.PackType)(1));
            w19.Position = 2;
            w19.Expand = false;
            w19.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.connectsubnet = new Gtk.Button();
            this.connectsubnet.CanFocus = true;
            this.connectsubnet.Name = "connectsubnet";
            this.connectsubnet.UseStock = true;
            this.connectsubnet.UseUnderline = true;
            this.connectsubnet.Label = "gtk-connect";
            this.hbox4.Add(this.connectsubnet);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox4[this.connectsubnet]));
            w20.PackType = ((Gtk.PackType)(1));
            w20.Position = 3;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.desconnectsubnet = new Gtk.Button();
            this.desconnectsubnet.CanFocus = true;
            this.desconnectsubnet.Name = "desconnectsubnet";
            this.desconnectsubnet.UseStock = true;
            this.desconnectsubnet.UseUnderline = true;
            this.desconnectsubnet.Label = "gtk-disconnect";
            this.hbox4.Add(this.desconnectsubnet);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.hbox4[this.desconnectsubnet]));
            w21.PackType = ((Gtk.PackType)(1));
            w21.Position = 4;
            w21.Expand = false;
            w21.Fill = false;
            this.vbox1.Add(this.hbox4);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.connectiondetails = new Gtk.Expander(null);
            this.connectiondetails.CanFocus = true;
            this.connectiondetails.Name = "connectiondetails";
            this.connectiondetails.Expanded = true;
            // Container child connectiondetails.Gtk.Container+ContainerChild
            this.notebook = new Gtk.Notebook();
            this.notebook.CanFocus = true;
            this.notebook.Name = "notebook";
            this.notebook.CurrentPage = 2;
            // Container child notebook.Gtk.Notebook+NotebookChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 286;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.addresstreeview = new Gtk.TreeView();
            this.addresstreeview.CanFocus = true;
            this.addresstreeview.Name = "addresstreeview";
            this.GtkScrolledWindow.Add(this.addresstreeview);
            this.vbox3.Add(this.GtkScrolledWindow);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
            w24.Position = 0;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            this.hbuttonbox1.Homogeneous = true;
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.addp_address = new Gtk.Button();
            this.addp_address.CanFocus = true;
            this.addp_address.Name = "addp_address";
            this.addp_address.UseStock = true;
            this.addp_address.UseUnderline = true;
            this.addp_address.Label = "gtk-add";
            this.hbuttonbox1.Add(this.addp_address);
            Gtk.ButtonBox.ButtonBoxChild w25 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.addp_address]));
            w25.Expand = false;
            w25.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.removep_address = new Gtk.Button();
            this.removep_address.CanFocus = true;
            this.removep_address.Name = "removep_address";
            this.removep_address.UseStock = true;
            this.removep_address.UseUnderline = true;
            this.removep_address.Label = "gtk-remove";
            this.hbuttonbox1.Add(this.removep_address);
            Gtk.ButtonBox.ButtonBoxChild w26 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.removep_address]));
            w26.Position = 1;
            w26.Expand = false;
            w26.Fill = false;
            this.vbox3.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox1]));
            w27.Position = 1;
            w27.Expand = false;
            w27.Fill = false;
            this.hpaned1.Add(this.vbox3);
            Gtk.Paned.PanedChild w28 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox3]));
            w28.Resize = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), true);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.addressvalue = new Gtk.Entry();
            this.addressvalue.CanFocus = true;
            this.addressvalue.Name = "addressvalue";
            this.addressvalue.IsEditable = true;
            this.addressvalue.InvisibleChar = '●';
            this.table1.Add(this.addressvalue);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table1[this.addressvalue]));
            w29.TopAttach = ((uint)(1));
            w29.BottomAttach = ((uint)(2));
            w29.LeftAttach = ((uint)(1));
            w29.RightAttach = ((uint)(2));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Type:");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Value:");
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(2));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.manageaddress = new Gtk.Button();
            this.manageaddress.CanFocus = true;
            this.manageaddress.Name = "manageaddress";
            this.manageaddress.UseUnderline = true;
            // Container child manageaddress.Gtk.Container+ContainerChild
            Gtk.Alignment w32 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w33 = new Gtk.HBox();
            w33.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w34 = new Gtk.Image();
            w34.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_navigator-references", Gtk.IconSize.Button, 16);
            w33.Add(w34);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w36 = new Gtk.Label();
            w36.LabelProp = Mono.Unix.Catalog.GetString("Manage System Addresses");
            w36.UseUnderline = true;
            w33.Add(w36);
            w32.Add(w33);
            this.manageaddress.Add(w32);
            this.table1.Add(this.manageaddress);
            Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table1[this.manageaddress]));
            w40.TopAttach = ((uint)(2));
            w40.BottomAttach = ((uint)(3));
            w40.RightAttach = ((uint)(2));
            w40.XOptions = ((Gtk.AttachOptions)(4));
            w40.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.tplist = Gtk.ComboBoxEntry.NewText();
            this.tplist.Name = "tplist";
            this.table1.Add(this.tplist);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table1[this.tplist]));
            w41.LeftAttach = ((uint)(1));
            w41.RightAttach = ((uint)(2));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            this.hpaned1.Add(this.table1);
            this.notebook.Add(this.hpaned1);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.TooltipMarkup = "IED's Address connection information to the current subnetwork";
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Address");
            this.notebook.SetTabLabel(this.hpaned1, this.label2);
            this.label2.ShowAll();
            // Container child notebook.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Select a Physical Connection:");
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w44.Position = 0;
            w44.Expand = false;
            w44.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.physclist = Gtk.ComboBox.NewText();
            this.physclist.Name = "physclist";
            this.hbox1.Add(this.physclist);
            Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox1[this.physclist]));
            w45.Position = 1;
            w45.Expand = false;
            w45.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            this.hbuttonbox2.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.addphysconn = new Gtk.Button();
            this.addphysconn.CanFocus = true;
            this.addphysconn.Name = "addphysconn";
            this.addphysconn.UseStock = true;
            this.addphysconn.UseUnderline = true;
            this.addphysconn.Label = "gtk-add";
            this.hbuttonbox2.Add(this.addphysconn);
            Gtk.ButtonBox.ButtonBoxChild w46 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.addphysconn]));
            w46.Expand = false;
            w46.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.removephysconn = new Gtk.Button();
            this.removephysconn.CanFocus = true;
            this.removephysconn.Name = "removephysconn";
            this.removephysconn.UseStock = true;
            this.removephysconn.UseUnderline = true;
            this.removephysconn.Label = "gtk-remove";
            this.hbuttonbox2.Add(this.removephysconn);
            Gtk.ButtonBox.ButtonBoxChild w47 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.removephysconn]));
            w47.Position = 1;
            w47.Expand = false;
            w47.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.editphysconn = new Gtk.Button();
            this.editphysconn.CanFocus = true;
            this.editphysconn.Name = "editphysconn";
            this.editphysconn.UseStock = true;
            this.editphysconn.UseUnderline = true;
            this.editphysconn.Label = "gtk-edit";
            this.hbuttonbox2.Add(this.editphysconn);
            Gtk.ButtonBox.ButtonBoxChild w48 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.editphysconn]));
            w48.Position = 2;
            w48.Expand = false;
            w48.Fill = false;
            this.hbox1.Add(this.hbuttonbox2);
            Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.hbox1[this.hbuttonbox2]));
            w49.Position = 2;
            this.vbox4.Add(this.hbox1);
            Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
            w50.Position = 0;
            w50.Expand = false;
            w50.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hpaned2 = new Gtk.HPaned();
            this.hpaned2.CanFocus = true;
            this.hpaned2.Name = "hpaned2";
            this.hpaned2.Position = 376;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.GtkScrolledWindow2 = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
            this.GtkScrolledWindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
            this.physicaltreeview = new Gtk.TreeView();
            this.physicaltreeview.CanFocus = true;
            this.physicaltreeview.Name = "physicaltreeview";
            this.GtkScrolledWindow2.Add(this.physicaltreeview);
            this.vbox5.Add(this.GtkScrolledWindow2);
            Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow2]));
            w52.Position = 0;
            // Container child vbox5.Gtk.Box+BoxChild
            this.hbuttonbox3 = new Gtk.HButtonBox();
            this.hbuttonbox3.Name = "hbuttonbox3";
            this.hbuttonbox3.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.addp_physconn = new Gtk.Button();
            this.addp_physconn.CanFocus = true;
            this.addp_physconn.Name = "addp_physconn";
            this.addp_physconn.UseStock = true;
            this.addp_physconn.UseUnderline = true;
            this.addp_physconn.Label = "gtk-add";
            this.hbuttonbox3.Add(this.addp_physconn);
            Gtk.ButtonBox.ButtonBoxChild w53 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.addp_physconn]));
            w53.Expand = false;
            w53.Fill = false;
            // Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
            this.removep_physconn = new Gtk.Button();
            this.removep_physconn.CanFocus = true;
            this.removep_physconn.Name = "removep_physconn";
            this.removep_physconn.UseStock = true;
            this.removep_physconn.UseUnderline = true;
            this.removep_physconn.Label = "gtk-remove";
            this.hbuttonbox3.Add(this.removep_physconn);
            Gtk.ButtonBox.ButtonBoxChild w54 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3[this.removep_physconn]));
            w54.Position = 1;
            w54.Expand = false;
            w54.Fill = false;
            this.vbox5.Add(this.hbuttonbox3);
            Gtk.Box.BoxChild w55 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbuttonbox3]));
            w55.Position = 1;
            w55.Expand = false;
            w55.Fill = false;
            this.hpaned2.Add(this.vbox5);
            Gtk.Paned.PanedChild w56 = ((Gtk.Paned.PanedChild)(this.hpaned2[this.vbox5]));
            w56.Resize = false;
            // Container child hpaned2.Gtk.Paned+PanedChild
            this.table3 = new Gtk.Table(((uint)(3)), ((uint)(2)), true);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Value:");
            this.table3.Add(this.label11);
            Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table3[this.label11]));
            w57.TopAttach = ((uint)(1));
            w57.BottomAttach = ((uint)(2));
            w57.XOptions = ((Gtk.AttachOptions)(4));
            w57.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Type:");
            this.table3.Add(this.label12);
            Gtk.Table.TableChild w58 = ((Gtk.Table.TableChild)(this.table3[this.label12]));
            w58.XOptions = ((Gtk.AttachOptions)(4));
            w58.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.managephysicalconnections = new Gtk.Button();
            this.managephysicalconnections.CanFocus = true;
            this.managephysicalconnections.Name = "managephysicalconnections";
            this.managephysicalconnections.UseUnderline = true;
            // Container child managephysicalconnections.Gtk.Container+ContainerChild
            Gtk.Alignment w59 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w60 = new Gtk.HBox();
            w60.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w61 = new Gtk.Image();
            w61.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_navigator-references", Gtk.IconSize.Button, 16);
            w60.Add(w61);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w63 = new Gtk.Label();
            w63.LabelProp = Mono.Unix.Catalog.GetString("Manage System Physical Connections");
            w63.UseUnderline = true;
            w60.Add(w63);
            w59.Add(w60);
            this.managephysicalconnections.Add(w59);
            this.table3.Add(this.managephysicalconnections);
            Gtk.Table.TableChild w67 = ((Gtk.Table.TableChild)(this.table3[this.managephysicalconnections]));
            w67.TopAttach = ((uint)(2));
            w67.BottomAttach = ((uint)(3));
            w67.RightAttach = ((uint)(2));
            w67.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.physicalvalue = new Gtk.Entry();
            this.physicalvalue.CanFocus = true;
            this.physicalvalue.Name = "physicalvalue";
            this.physicalvalue.IsEditable = true;
            this.physicalvalue.InvisibleChar = '●';
            this.table3.Add(this.physicalvalue);
            Gtk.Table.TableChild w68 = ((Gtk.Table.TableChild)(this.table3[this.physicalvalue]));
            w68.TopAttach = ((uint)(1));
            w68.BottomAttach = ((uint)(2));
            w68.LeftAttach = ((uint)(1));
            w68.RightAttach = ((uint)(2));
            w68.XOptions = ((Gtk.AttachOptions)(4));
            w68.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.tplist_physical = Gtk.ComboBoxEntry.NewText();
            this.tplist_physical.Name = "tplist_physical";
            this.table3.Add(this.tplist_physical);
            Gtk.Table.TableChild w69 = ((Gtk.Table.TableChild)(this.table3[this.tplist_physical]));
            w69.LeftAttach = ((uint)(1));
            w69.RightAttach = ((uint)(2));
            w69.XOptions = ((Gtk.AttachOptions)(4));
            w69.YOptions = ((Gtk.AttachOptions)(4));
            this.hpaned2.Add(this.table3);
            this.vbox4.Add(this.hpaned2);
            Gtk.Box.BoxChild w71 = ((Gtk.Box.BoxChild)(this.vbox4[this.hpaned2]));
            w71.Position = 1;
            this.notebook.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w72 = ((Gtk.Notebook.NotebookChild)(this.notebook[this.vbox4]));
            w72.Position = 1;
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.TooltipMarkup = "IED's Physical Connections to the current subnetwork";
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Physical");
            this.notebook.SetTabLabel(this.vbox4, this.label5);
            this.label5.ShowAll();
            // Container child notebook.Gtk.Notebook+NotebookChild
            this.gselistviewer = new OpenSASUI.GSEListViewer();
            this.gselistviewer.Events = ((Gdk.EventMask)(256));
            this.gselistviewer.Name = "gselistviewer";
            this.notebook.Add(this.gselistviewer);
            Gtk.Notebook.NotebookChild w73 = ((Gtk.Notebook.NotebookChild)(this.notebook[this.gselistviewer]));
            w73.Position = 2;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.TooltipMarkup = "Generic Substation Events Published by this IED";
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("GSE");
            this.notebook.SetTabLabel(this.gselistviewer, this.label3);
            this.label3.ShowAll();
            // Notebook tab
            Gtk.Label w74 = new Gtk.Label();
            w74.Visible = true;
            this.notebook.Add(w74);
            this.label4 = new Gtk.Label();
            this.label4.TooltipMarkup = "Sample Values Published by this IED";
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("SMV");
            this.notebook.SetTabLabel(w74, this.label4);
            this.label4.ShowAll();
            this.connectiondetails.Add(this.notebook);
            this.GtkLabel23 = new Gtk.Label();
            this.GtkLabel23.Name = "GtkLabel23";
            this.GtkLabel23.LabelProp = Mono.Unix.Catalog.GetString("Connection Details");
            this.GtkLabel23.UseUnderline = true;
            this.connectiondetails.LabelWidget = this.GtkLabel23;
            this.vbox1.Add(this.connectiondetails);
            Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(this.vbox1[this.connectiondetails]));
            w76.Position = 2;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
