
// This file has been generated by the GUI designer. Do not modify.
namespace OpenSASUI
{
	public partial class SclEditor
	{
		private global::Gtk.HPaned hpaned3;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::OpenSASUI.SclTreeView scltreeview;

		private global::Gtk.Notebook notebook2;

		private global::Gtk.VBox NothingContainer;

		private global::Gtk.Label label4;

		private global::OpenSASUI.IEDEditor iededitor;

		private global::Gtk.Label label26;

		private global::Gtk.VBox vbox10;

		private global::OpenSASUI.SclCommManager sclcommmanager;

		private global::Gtk.Label label35;

		private global::OpenSASUI.HistoryEditor historyeditor;

		private global::Gtk.Label label36;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenSASUI.SclEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OpenSASUI.SclEditor";
			// Container child OpenSASUI.SclEditor.Gtk.Container+ContainerChild
			this.hpaned3 = new global::Gtk.HPaned ();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 218;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.scltreeview = new global::OpenSASUI.SclTreeView ();
			this.scltreeview.CanFocus = true;
			this.scltreeview.Name = "scltreeview";
			this.scrolledwindow1.Add (this.scltreeview);
			this.hpaned3.Add (this.scrolledwindow1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned3[this.scrolledwindow1]));
			w2.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 3;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.NothingContainer = new global::Gtk.VBox ();
			this.NothingContainer.Name = "NothingContainer";
			this.NothingContainer.Spacing = 6;
			this.notebook2.Add (this.NothingContainer);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Nothing");
			this.notebook2.SetTabLabel (this.NothingContainer, this.label4);
			this.label4.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.iededitor = new global::OpenSASUI.IEDEditor ();
			this.iededitor.Events = ((global::Gdk.EventMask)(256));
			this.iededitor.Name = "iededitor";
			this.notebook2.Add (this.iededitor);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.iededitor]));
			w4.Position = 1;
			w4.TabExpand = true;
			// Notebook tab
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("IED Editor");
			this.notebook2.SetTabLabel (this.iededitor, this.label26);
			this.label26.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.sclcommmanager = new global::OpenSASUI.SclCommManager ();
			this.sclcommmanager.Events = ((global::Gdk.EventMask)(256));
			this.sclcommmanager.Name = "sclcommmanager";
			this.vbox10.Add (this.sclcommmanager);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.sclcommmanager]));
			w5.Position = 0;
			this.notebook2.Add (this.vbox10);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.vbox10]));
			w6.Position = 2;
			// Notebook tab
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("Communications");
			this.notebook2.SetTabLabel (this.vbox10, this.label35);
			this.label35.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.historyeditor = new global::OpenSASUI.HistoryEditor ();
			this.historyeditor.Events = ((global::Gdk.EventMask)(256));
			this.historyeditor.Name = "historyeditor";
			this.notebook2.Add (this.historyeditor);
			global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2[this.historyeditor]));
			w7.Position = 3;
			// Notebook tab
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("History");
			this.notebook2.SetTabLabel (this.historyeditor, this.label36);
			this.label36.ShowAll ();
			this.hpaned3.Add (this.notebook2);
			this.Add (this.hpaned3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
