
// This file has been generated by the GUI designer. Do not modify.
namespace OpenSASUI
{
	public partial class IEDEditor
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Image image1;

		private global::Gtk.Label DeviceInformationLabel;

		private global::Gtk.Notebook notebook;

		private global::Gtk.HPaned hpaned;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview;

		private global::Gtk.Table table1;

		private global::Gtk.Entry iedconfigrevision;

		private global::Gtk.ComboBoxEntry iedmanufacturer;

		private global::Gtk.Entry iedname;

		private global::Gtk.Label label10;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label label7;

		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.ComboBox accesspointlist;

		private global::Gtk.Button button1;

		private global::Gtk.Button button5;

		private global::OpenSASUI.APEditor accesspointeditor;

		private global::Gtk.Label label19;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label17;

		private global::Gtk.ComboBox ldlist;

		private global::Gtk.Button removeld;

		private global::Gtk.Button addld;

		private global::OpenSASUI.LDEditor ldedit;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.Label label25;

		private global::Gtk.Label DeviceDescription;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenSASUI.IEDEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "OpenSASUI.IEDEditor";
			// Container child OpenSASUI.IEDEditor.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(9));
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("OpenSASUI.ied-64x36.png");
			this.hbox1.Add (this.image1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.DeviceInformationLabel = new global::Gtk.Label ();
			this.DeviceInformationLabel.Name = "DeviceInformationLabel";
			this.DeviceInformationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("IED Information.\nManufacturer.\nConfiguration Revision.");
			this.DeviceInformationLabel.UseMarkup = true;
			this.DeviceInformationLabel.Selectable = true;
			this.hbox1.Add (this.DeviceInformationLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.DeviceInformationLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 1;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.hpaned = new global::Gtk.HPaned ();
			this.hpaned.CanFocus = true;
			this.hpaned.Name = "hpaned";
			this.hpaned.Position = 125;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView ();
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow.Add (this.treeview);
			this.hpaned.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned[this.GtkScrolledWindow]));
			w5.Resize = false;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.iedconfigrevision = new global::Gtk.Entry ();
			this.iedconfigrevision.CanFocus = true;
			this.iedconfigrevision.Name = "iedconfigrevision";
			this.iedconfigrevision.IsEditable = true;
			this.iedconfigrevision.InvisibleChar = '●';
			this.table1.Add (this.iedconfigrevision);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.iedconfigrevision]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.iedmanufacturer = global::Gtk.ComboBoxEntry.NewText ();
			this.iedmanufacturer.AppendText ("");
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("ABB"));
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("AREVA"));
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("GENERAL ELECTRIC"));
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("INGETEAM"));
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("SEL"));
			this.iedmanufacturer.AppendText (global::Mono.Unix.Catalog.GetString ("SIEMENS"));
			this.iedmanufacturer.TooltipMarkup = "Select the manufacturer";
			this.iedmanufacturer.Name = "iedmanufacturer";
			this.table1.Add (this.iedmanufacturer);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.iedmanufacturer]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.iedname = new global::Gtk.Entry ();
			this.iedname.TooltipMarkup = "IED's name";
			this.iedname.CanFocus = true;
			this.iedname.Name = "iedname";
			this.iedname.IsEditable = true;
			this.iedname.InvisibleChar = '●';
			this.table1.Add (this.iedname);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.iedname]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Conf. Rev.:");
			this.table1.Add (this.label10);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label10]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("IED Name:");
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label8]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Manufacturer:");
			this.table1.Add (this.label9);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label9]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hpaned.Add (this.table1);
			this.notebook.Add (this.hpaned);
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("IED");
			this.notebook.SetTabLabel (this.hpaned, this.label7);
			this.label7.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Access Point:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.accesspointlist = global::Gtk.ComboBox.NewText ();
			this.accesspointlist.Name = "accesspointlist";
			this.hbox2.Add (this.accesspointlist);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.accesspointlist]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseStock = true;
			this.button1.UseUnderline = true;
			this.button1.Label = "gtk-add";
			this.hbox2.Add (this.button1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button1]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseStock = true;
			this.button5.UseUnderline = true;
			this.button5.Label = "gtk-remove";
			this.hbox2.Add (this.button5);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button5]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.accesspointeditor = new global::OpenSASUI.APEditor ();
			this.accesspointeditor.Events = ((global::Gdk.EventMask)(256));
			this.accesspointeditor.Name = "accesspointeditor";
			this.vbox1.Add (this.accesspointeditor);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.accesspointeditor]));
			w19.Position = 1;
			this.notebook.Add (this.vbox1);
			global::Gtk.Notebook.NotebookChild w20 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.vbox1]));
			w20.Position = 1;
			// Notebook tab
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Communications");
			this.notebook.SetTabLabel (this.vbox1, this.label19);
			this.label19.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(3));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Logical Device");
			this.hbox5.Add (this.label17);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label17]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.ldlist = global::Gtk.ComboBox.NewText ();
			this.ldlist.TooltipMarkup = "Select an existing LD In the IED";
			this.ldlist.Name = "ldlist";
			this.hbox5.Add (this.ldlist);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.ldlist]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.removeld = new global::Gtk.Button ();
			this.removeld.CanFocus = true;
			this.removeld.Name = "removeld";
			this.removeld.UseStock = true;
			this.removeld.UseUnderline = true;
			this.removeld.Label = "gtk-remove";
			this.hbox5.Add (this.removeld);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.removeld]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.addld = new global::Gtk.Button ();
			this.addld.CanFocus = true;
			this.addld.Name = "addld";
			this.addld.UseStock = true;
			this.addld.UseUnderline = true;
			this.addld.Label = "gtk-add";
			this.hbox5.Add (this.addld);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.addld]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox5.Add (this.hbox5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.ldedit = new global::OpenSASUI.LDEditor ();
			this.ldedit.Events = ((global::Gdk.EventMask)(256));
			this.ldedit.Name = "ldedit";
			this.vbox5.Add (this.ldedit);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.ldedit]));
			w26.Position = 1;
			this.notebook.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w27 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.vbox5]));
			w27.Position = 2;
			// Notebook tab
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Logical Devices");
			this.notebook.SetTabLabel (this.vbox5, this.label23);
			this.label23.ShowAll ();
			// Notebook tab
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w28.Visible = true;
			this.notebook.Add (w28);
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Data Type Templates");
			this.notebook.SetTabLabel (w28, this.label24);
			this.label24.ShowAll ();
			// Notebook tab
			global::Gtk.Label w29 = new global::Gtk.Label ();
			w29.Visible = true;
			this.notebook.Add (w29);
			this.label25 = new global::Gtk.Label ();
			this.label25.TooltipMarkup = "View and Edit Private nodes on current IED";
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Private");
			this.notebook.SetTabLabel (w29, this.label25);
			this.label25.ShowAll ();
			this.vbox3.Add (this.notebook);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.notebook]));
			w30.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.DeviceDescription = new global::Gtk.Label ();
			this.DeviceDescription.Name = "DeviceDescription";
			this.DeviceDescription.Xalign = 0f;
			this.DeviceDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("IED Description");
			this.DeviceDescription.UseMarkup = true;
			this.DeviceDescription.Selectable = true;
			this.vbox3.Add (this.DeviceDescription);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.DeviceDescription]));
			w31.PackType = ((global::Gtk.PackType)(1));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
