
// This file has been generated by the GUI designer. Do not modify.
namespace OpenSASConfigurator
{
	public partial class OpenProgess
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label label;

		private global::Gtk.ProgressBar progressbar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget OpenSASConfigurator.OpenProgess
			this.Name = "OpenSASConfigurator.OpenProgess";
			this.Title = global::Mono.Unix.Catalog.GetString ("Opening an SCL File");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child OpenSASConfigurator.OpenProgess.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("Opening an SCL File");
			this.vbox1.Add (this.label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.progressbar = new global::Gtk.ProgressBar ();
			this.progressbar.Name = "progressbar";
			this.vbox1.Add (this.progressbar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.progressbar]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(20));
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 133;
			this.Show ();
		}
	}
}
